### ISSUE TITLE
Adding env variables to the pack command

### ISSUE THREAD

**Issue by omearaj** [mamezou-tech/buildpacks-action#4]
Do you have plans to add env variables to this action? Many of the buildpack features can be customized using the -e to specify a version of Java etc. Example

pack build repo/image:v1 -B gcr.io/paketo-buildpacks/builder:base -e BP_JVM_VERSION=8.*

**Comment by kondoumh** [comment]
I will add an input value so that you can specify some environment variables.

**Comment by omearaj** [comment]
Thank you. Specifying the Java runtime version, for example, is required for many of my apps. I look forward to using it in action.

**Comment by omearaj** [comment]
Thank you, it worked perfectly! Any interest in adding the ability to build and push the image?

**Comment by kondoumh** [comment]
> Any interest in adding the ability to build and push the image?

You mean so that not only builds, but pushes can be performed within this action?
This action is a command wrapper for buildpacks, so it is only responsible for building. Pushing can be done through another action or through the docker CLI.
